### ISSUE TITLE
errors during installation

### ISSUE THREAD

**Issue by blakew** [mathiasbynens/base64#10]
npm version: 5.5.1
node version: 8.6.0
OS: macOS 10.12.6

```
$ npm install --save base64

> node-gyp rebuild

  CXX(target) Release/obj.target/base64/base64.o
../base64.cc:13:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
~/.node-gyp/8.6.0/include/node/v8.h:876:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../base64.cc:14:52: error: no member named 'New' in 'v8::String'
    return ThrowException(Exception::Error(String::New(msg)));
                                           ~~~~~~~~^
../base64.cc:122:29: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
base64_encode_binding(const Arguments &args)
                            ^~~~~~~~~
                            v8::internal::Arguments
~/.node-gyp/8.6.0/include/node/v8.h:141:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../base64.cc:124:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/blakewillmarth/.node-gyp/8.6.0/include/node/v8.h:876:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../base64.cc:127:13: error: member access into incomplete type 'const v8::internal::Arguments'
    if (args.Length() != 1)
            ^
~/.node-gyp/8.6.0/include/node/v8.h:141:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../base64.cc:130:33: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    if (Buffer::HasInstance(args[0])) {
                            ~~~~^~
../base64.cc:131:45: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        v8::Handle<v8::Object> buffer = args[0]->ToObject();
                                        ~~~~^~
../base64.cc:137:18: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    else if (args[0]->IsString()) {
             ~~~~^~
../base64.cc:138:38: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        String::Utf8Value v8str (args[0]->ToString());
                                 ~~~~^~
../base64.cc:144:33: error: no member named 'New' in 'v8::String'
    Local<String> ret = String::New(str);
                        ~~~~~~~~^
../base64.cc:146:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(ret);
           ~~~~~ ^
../base64.cc:150:29: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
base64_decode_binding(const Arguments &args)
                            ^~~~~~~~~
                            v8::internal::Arguments
~/.node-gyp/8.6.0/include/node/v8.h:141:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../base64.cc:152:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/blakewillmarth/.node-gyp/8.6.0/include/node/v8.h:876:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../base64.cc:155:13: error: member access into incomplete type 'const v8::internal::Arguments'
    if (args.Length() < 1)
            ^
/Users/blakewillmarth/.node-gyp/8.6.0/include/node/v8.h:141:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../base64.cc:160:33: error: type 'const v8::internal::Arguments' does not provide a subscript operator
    if (Buffer::HasInstance(args[0])) { // buffer
                            ~~~~^~
../base64.cc:161:45: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        v8::Handle<v8::Object> buffer = args[0]->ToObject();
                                        ~~~~^~
../base64.cc:170:27: error: expected ';' after expression
        String::AsciiValue b64data(args[0]->ToString());
                          ^
                          ;
../base64.cc:170:17: error: no member named 'AsciiValue' in 'v8::String'
        String::AsciiValue b64data(args[0]->ToString());
        ~~~~~~~~^
../base64.cc:170:40: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        String::AsciiValue b64data(args[0]->ToString());
                                   ~~~~^~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/base64/base64.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ...
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! base64@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the base64@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by mathiasbynens** [comment]
You’re installing a different package.

Please follow https://github.com/mathiasbynens/base64#installation.
